// Attribute mapping reference (not a runtime dependency):
// https://github.com/ByteBard97/roll20-5e-npc-json-importer/blob/master/scripts/5e_NPC_JSON_Importer.js
// Troubleshooting and known limitations:
// https://github.com/ByteBard97/roll20-5e-npc-json-importer/blob/master/README.md
// Guidance is written for our execute_roll20 workflow, not the importer's chat commands.
export const NPC_2014_INSTRUCTIONS = [
  "#### Build a complete NPC on the 2014 Roll20 sheet",
  "Implement this recipe directly through execute_roll20 using standard Mod objects and functions. The reference importer need not be installed; do not call its private helpers or chat commands.",
  "When asked to create an NPC, carry the request through to a usable character sheet, not just a proposed stat block or a character with a name. Pick an ancestry-appropriate fantasy name unless the GM supplies one or requests otherwise. Choose reasonable ability scores, equipment, proficiencies, subclass, class features, and other unspecified details yourself, respecting campaign instructions. Briefly report the choices afterward rather than asking the GM to fill out a character-building questionnaire.",
  "For this 2014-sheet recipe, default to 2014 D&D 5e rules unless the GM explicitly requests 2024/5.5e. Rules edition and sheet technology are distinct: never silently override an explicit edition request. Apply this recipe only to a positively identified 2014 sheet, or when creating in a legacy campaign. In a new-style or mixed campaign, createObj still produces a 2024 sheet; do not try to force this recipe onto it or switch campaign settings. Follow the separate Beacon guidance for that sheet, and report any unsupported creation steps.",
  "A class level is not a challenge rating. A 'level 3 gnome warlock NPC' means a 3rd-level warlock represented using the NPC sheet, not a CR 3 monster. Give it level-appropriate class and racial features, hit points, proficiency, and Pact Magic. Set CR/XP only when requested or when you can justify an estimate; label estimates. Never use a monster CR benchmark's HP or damage as the class character's stats merely because its level is the same number.",
  "##### Creation and worker sequencing",
  [
    "- Inspect the campaign and any target character first. For a new NPC, create a character with its chosen name and brief bio; keep controlledby and inplayerjournals empty unless the GM requested sharing. Return its actual character ID early and use that ID in subsequent calls.",
    "- Use a local attribute-upsert helper: findObjs({ type: 'attribute', characterid: characterId, name })[0], or createObj('attribute', { characterid: characterId, name }) if absent; then call attribute.setWithWorker({ current: value }) (and max when appropriate). Reuse attributes rather than making duplicate names. Merely passing current to createObj does not replace an explicit worker-triggering write.",
    "- Initialize npc='1', charactersheet_type='npc', character_name and npc_name. Apply the Charactermancer values above: l1mancer_status='completed', mancer_confirm_flag='', mancer_cancel='on'. Set npc_options-flag='0' to close the NPC editor after setup. Do not overwrite version, sheet_version, npc_version, or sheet-identity markers with the importer's hard-coded versions.",
    "- Batch related source-field writes. When waiting for derived fields, register onSheetWorkerCompleted(callback) BEFORE the setWithWorker calls, and wrap completion in an awaited Promise with a bounded timeout. setWithWorker itself is not an awaitable worker-completion promise. Re-read derived fields after completion; the callback alone is not proof that every field is correct.",
    "- Allow for asynchronous initialization. The reference importer reports roughly 5–25 seconds for complex NPCs, so a fixed one-second sleep is not a completion guarantee. Use a few bounded phases (create/initialize, populate, verify/repair); return progress and IDs before the tool deadline. Never leave a fire-and-forget timer to finish creation after reporting success. If a tool times out, inspect the known character before deciding what remains; do not repeat the whole creation script or create a duplicate.",
  ].join("\n"),
  "##### Core attributes and calculated values",
  [
    "- Identity: npc_size, npc_type, npc_alignment; record ancestry, class/level, subclass and equipment in the bio and relevant traits so the NPC's build is evident.",
    "- Defenses and movement: npc_ac (numeric AC), npc_actype and npc_ac_notes (armor explanation), hp with both current and max, npc_hp, npc_hpbase, npc_hpformula (hit-dice expression), and npc_speed. NPC AC uses npc_ac; writing only the PC ac field is insufficient.",
    "- Abilities: strength, dexterity, constitution, intelligence, wisdom, charisma and their corresponding <ability>_base values. Verify <ability>_mod = floor((score - 10) / 2) after workers run.",
    "- Proficiency: for a class-level build use pb_type='custom', pb_custom and pb equal to its numeric proficiency bonus, plus npc_pb as its signed display bonus. Derive it from class level, not an assumed CR. For a stat-block monster use its actual proficiency and npc_challenge/npc_xp where known.",
    "- Saves: the importer populates npc_<short>_save, npc_<short>_save_base, npc_<short>_save_flag (short = str/dex/con/int/wis/cha), plus <full>_save_bonus. The numeric field is the TOTAL save bonus; _base is its signed display value. Its flags are '0' for the ability modifier alone, '1' for modifier plus proficiency, '2' for a custom total. It also mirrors npc_<full>_save/_base/_flag. Check worker output rather than assuming every mirrored field is necessary. npc_saving_flag is a bit mask: str=1, dex=2, con=4, int=8, wis=16, cha=32 for displayed non-default saves.",
    "- Skills: use the exact sheet keys (including animal_handling and sleight_of_hand). For each trained/custom skill populate npc_<skill>, npc_<skill>_base, npc_<skill>_bonus, npc_<skill>_flag and <skill>_bonus; use the total bonus, including expertise if applicable, not just proficiency. Set npc_skills_flag='1' when displaying skills. Do not collapse multiword names into animalhandling or sleightofhand. Verify passive_wisdom = 10 + total Perception bonus and initiative_bonus = Dexterity modifier plus actual initiative features.",
    "- Other stat-block fields: npc_vulnerabilities, npc_resistances, npc_immunities, npc_condition_immunities, npc_senses (include darkvision and passive Perception where appropriate), npc_languages. Preserve full qualifications such as advantage only on certain saves as traits; do not turn conditional advantages into permanent numeric bonuses or immunities.",
  ].join("\n"),
  "##### Traits, actions, and useful shortcuts",
  "Create real repeating rows so the NPC sheet itself is usable. Attribute names have the form repeating_<section>_<rowId>_<field>. Use one stable unique ID per row: if generateRowID is unavailable, generate a '-' followed by 19 random alphanumeric characters and check for a collision. Do not assume generateRowID is a Mod global. Return and reuse row IDs during repairs. Upsert _reporder_repeating_<section> as a comma-separated list of row IDs; preserve existing order and append new IDs when editing.",
  [
    "- Traits: repeating_npctrait rows use name and desc. Trigger setWithWorker on desc so the displayed text initializes. Include racial features, class/subclass features, invocations, pact boon, resource/recharge rules, and a concise spellcasting trait as applicable.",
    "- Actions: repeating_npcaction rows use name and description (not desc). Text-only actions should preserve all mechanics, including save DC/ability, targets, conditions, duration, and recharge. Multiattack should explain its component attacks, not invent a single combined attack roll.",
    "- Attack actions: set attack_flag='on', attack_type, attack_range, attack_target, attack_tohit (total numeric attack bonus), attack_damage (full dice expression including modifier), and attack_damagetype. For a second damage component use attack_damage2 and attack_damagetype2. Critical dice fields attack_crit/attack_crit2 must contain the extra dice only, not duplicated flat modifiers. Preserve riders and saving throws in description.",
    "- Check the worker-generated attack_tohitrange, attack_onhit, damage_flag, attack_display_flag, attack_options and rollbase. The importer's display flag is '{{attack=1}}', and damage_flag uses '{{damage=1}} {{dmg1flag=1}}' plus '{{dmg2flag=1}}' when needed. Those are template fragments, not booleans. Do not blindly replace working worker-generated roll formulas.",
    "- Bonus actions: repeating_npcbonusaction; enable npcbonusactionsflag='1'. The importer fills name/description and mirrors them as wp_name/wp_description with corresponding wp_* attack fields and wp_rollbase. Inspect the actual initialized row to determine which fields/buttons this sheet version uses; do not assume its text-only bonus-action implementation automates bonus-action attacks.",
    "- Reactions: repeating_npcreaction with name and desc, with a worker-triggering desc write; enable npcreactionsflag='1'. Legendary actions, when appropriate, use repeating_npcaction-l and npc_legendary_actions for the per-round count. Preserve action costs and triggers. Do not grant legendary, mythic or lair actions to an ordinary class-level NPC merely because the sheet supports them.",
  ].join("\n"),
  "Provide character Ability objects (createObj('ability', { characterid: characterId, name, action, istokenaction: true })) for useful combat shortcuts: attacks, initiative, and frequently used actions/reactions. Prefer verified native sheet roll buttons referenced with %{characterId|buttonName}, including exact repeating row IDs. A rollbase ATTRIBUTE containing macro text is not automatically a callable button named rollbase: do not blindly copy the importer's %{characterId|repeating_..._rollbase} references. If the native button cannot be verified, create a self-contained Ability macro with fully qualified @{characterId|attributeName} references and explicit inline rolls for the attack/damage/save details. Never copy a row-local formula with unqualified @{name} or @{attack_tohit} into an Ability outside that row's context.",
  "Check that shortcut descriptions contain actual ability text, not the literal '1'. The importer writes show_desc='1' while some formulas interpolate @{show_desc} as the description; inspect the installed sheet's expected value and resolved output. Preserve or deliberately configure the sheet's whisper/advantage settings; dtype='full' enables automatic damage and critical rolls. Avoid unresolved rtype/wtype references to missing toggle attributes. Initiative shortcuts should use the initiative modifier and tracker behavior, not merely print a number. Keep complicated choices or conditional riders in readable output when full automation cannot represent them faithfully.",
  "##### Spellcasting and Pact Magic",
  "Set npcspellcastingflag='1', caster_level, and spellcasting_ability using the sheet formula (for Charisma, '@{charisma_mod}+'), after ability scores and proficiency are initialized. Populate lvl1_slots_total through lvl9_slots_total according to the actual build. A 2014 level-3 warlock has two 2nd-level Pact Magic slots, recovered on a short rest; do not give it the standard full-caster slot progression. Describe Pact Magic separately from racial/innate spells or at-will abilities. Choose appropriate known spells/cantrips and list them, their resource rules, and the selected invocations/pact boon in traits.",
  "Verify spell_save_dc = 8 + proficiency + casting modifier and spell_attack_bonus = proficiency + casting modifier, adjusted for real features. The README notes these may remain stale after import. First reapply spellcasting_ability with setWithWorker after dependent fields settle and re-read. If needed, try one bounded 'None' then restore cycle, awaiting worker completion between writes and restoring the intended value before returning. Do not endlessly toggle, assume a delay fixed it, or start by asking the GM to reload. Report any unresolved calculation explicitly.",
  "Individual spellbook population is NOT implemented by the reference importer. Manual spell entries need not require compendium access, but their exact repeating spell schema must be verified from the installed sheet or documentation before writing. Where that is unavailable, finish the NPC's core stats and spellcasting infrastructure, list its spells in the Spellcasting trait, and provide usable action/Ability shortcuts for spells whose mechanics are known. Do not invent a compendium-import API, promise spell-slot automation, or claim the spellbook is populated merely because a trait lists spell names. State precisely which spellbook entries or automation remain unavailable; do not block all NPC creation on compendium access.",
  "##### Verify and finish",
  "Re-read the created character and its attributes after workers settle. Check HP current/max, AC, abilities/modifiers, saves/skills, proficiency, spell DC/attack, repeating row names/descriptions/order, and the Ability objects and their referenced fields. Inspect for duplicate attributes, malformed dice, unresolved references, and lost riders. Successful attribute creation is not proof that roll buttons work; distinguish storage verification from an actually tested roll. Repair the known character and rows rather than generating replacements. Return a compact verification result with character ID, name, key stats, created actions/shortcuts, and any unresolved items, then give the GM a short completion summary.",
  "Skip art generation/import and do not claim to have uploaded artwork. If the GM supplied an existing token for this NPC, it can be linked via represents, configured with independent HP and AC bars, and saved with setDefaultTokenForCharacter after configuration; do not repurpose an unrelated token or expose its bars/name to players without a reason. Without an existing suitable token, complete the character and token-action Abilities and leave artwork/default-token setup for later.",
].join("\n\n");
